name: Build BWCE EAR and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Modifica se vuoi eseguire la pipeline su un altro branch

jobs:
  build-and-push:
    name: Build BWCE EAR and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11 (TIBCO BWCE supporta JDK 8/11)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Setup authentication for GitHub Packages
        run: |
          echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Build EAR with Maven
        run: mvn clean package -DskipTests --file='bwceTestApp.parent/pom.xml'

      - name: Verify EAR File
        run: ls -l /home/runner/work/bwce-test/bwce-test/bwceTestApp/target/*.ear
        
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build Docker Image
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}/images:bwce-test-github-${{ github.run_number }}" .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/images:bwce-test-github-1.0
